### ISSUE TITLE
Model parameters for after Genesis inflation

### ISSUE THREAD

**Issue by mastercyb** [cybercongress/cyber#1]
We need a model which allow us to concisely set up inflation parameters at Genesis. By default standard emission module allows setup the following parameters:
- inflation
- inflation rate change
- inflation min
- inflation max
- goal bonded

The simulation problem stems from the fact that at least 3 input parameters is hard to predict in advance:
- Which percent of drop to ethereum and cosmos will be claimed?
- Which percent of THC will be staked for receiving CYB?
- Which percent of CYB will be bonded for consensus?

Moreover, all this 3 ratios are dynamic in time. Depending on our assumptions parameters must be set in order to target inflation somewhat close to Ethereum: In the first 5 years it is wise to dilute 50% of Genesis tending to somewhat 10x dilution in 100 years.

Also as a result we need one simple chart chart showing which stake could have different cohorts of near Genesis participants in the following 100 years. In the white paper I think we need to illustrate it based on our exceptions of ratios with parameter proposals.

**Comment by xhipster** [comment]
@litvintech Did you delegate this task to Tolik or not?

**Comment by mastercyb** [comment]
Don [here](https://github.com/cybercongress/cybernomics)
