### ISSUE TITLE
White Paper translations

### ISSUE THREAD

**Issue by serejandmyself** [cybercongress/cyber#32]
We believe that it is vital to spread the information about our protocol for its success. It is important to get this information to as many people as possible, hence we need translations.

Bounty of 20 GCYB is offered for the WP translation via the [OBEP program](https://github.com/cybercongress/cyber-foundation/blob/master/evangelism/obep.md) 

We welcome all languages:

**Reserved:**
- [ ] Spanish: GaretJohanKay (warning)
- [x] Japanese: amaraly
- [x] Hindi: chaintee8989
- [x] German: airx3
- [x] Korean: ozidavici
- [x] Russian: Unbunplease 
- [x] Vietnamese: anobtc
- [x] Portuguese: Taskin 
- [x] Mandarin: Thompsona
- [ ] French: kapeldiamond (in work)
- [x] Thai: kiwsie
- [x] Filipino: Ken
- [ ] Turkish: bellaromg

**Waiting for confirmation:**

**Free:**
- [ ] Punjabi
- [ ] Indonesian: 
- [ ] Bengali
- [ ] Arabic
- [ ] Italian 
- [ ] Greek
- [ ] Hebrew
+ Anything else (just ask)

Do NOT start work unless you have been manually confirmed!

**Comment by Lotfy2** [comment]
Hello

I'm ready to do the Arabic translation if still needed

**Comment by serejandmyself** [comment]
> Hello
> 
> I'm ready to do the Arabic translation if still needed

Hey @Lotfy2 - yes, you can go ahead. The bounty is still for grabs too

**Comment by Lotfy2** [comment]
> > Hello
> > I'm ready to do the Arabic translation if still needed
> 
> Hey @Lotfy2 - yes, you can go ahead. The bounty is still for grabs too

Thank you @serejandmyself , I will do it ASPA.

**Comment by serejandmyself** [comment]
> > > Hello
> > > I'm ready to do the Arabic translation if still needed
> > 
> > 
> > Hey @Lotfy2 - yes, you can go ahead. The bounty is still for grabs too
> 
> Thank you @serejandmyself , I will do it ASPA.

Don't start just yet please. There is an update coming till the end of the week. I have reserved the translation for you though. I will ping you on here as soon as the update is pushed (2-3 days)

**Comment by vaultman542** [comment]
I want to make russian translation. Have a big experience

**Comment by serejandmyself** [comment]
> I want to make russian translation. Have a big experience

Do you mind showing any of your previous work In Russian (I mean crypto)? One example would be enough

**Comment by vaultman542** [comment]
https://bitcointalk.org/index.php?topic=5216188.msg53562043#msg53562043

**Comment by serejandmyself** [comment]
> https://bitcointalk.org/index.php?topic=5216188.msg53562043#msg53562043

You can surely go ahead if you wish (please do not start till I give the green light in a few days), however, please bare in mind, that the Russian translation will be the one with the most questions for us (what I mean is, this is a WP translation, so please be prepared for corrections while translating, etc)

**Comment by ozidavici** [comment]
I am willing to make Korean translation if needed. This is my previous job
https://docs.google.com/spreadsheets/d/1Y66YdNb76ZUxcLd8NNhEAtyAzuVTpenpYIyQ8Dfrm-U/edit?usp=sharing

**Comment by serejandmyself** [comment]
> I am willing to make Korean translation if needed. This is my previous job
> https://docs.google.com/spreadsheets/d/1Y66YdNb76ZUxcLd8NNhEAtyAzuVTpenpYIyQ8Dfrm-U/edit?usp=sharing

Hey! Korean is not taken yet! Please share a contact, I can contact you by to confirm your intentions

**Comment by ozidavici** [comment]
> > Tôi sẵn sàng thực hiện bản dịch tiếng Hàn nếu cần. Đây là công việc trước đây của tôi 
> > [https://docs.google.com/s Lansheet / d / 1Y66YdNb76ZUxcLd8NNhEAtyAzuVTpenpYIyQ8Dfrm-U/edit?usp=shaming](https://docs.google.com/spreadsheets/d/1Y66YdNb76ZUxcLd8NNhEAtyAzuVTpenpYIyQ8Dfrm-U/edit?usp=sharing)
> 
> Chào! Tiếng Hàn chưa được thực hiện! Hãy chia sẻ một liên hệ, tôi có thể liên lạc với bạn để xác nhận ý định của bạn

This is my email address: ozidavici@gmail.com
my telegram: @ozidavici
  Thanks very much

**Comment by ozidavici** [comment]
> Hey! Korean is not taken yet! Please share a contact, I can contact you by to confirm your intentions

This is my email address: ozidavici@gmail.com
my telegram: @ozidavici
  Thanks very much

**Comment by serejandmyself** [comment]
@Lotfy2 can you provide me your contact please?

**Comment by Lotfy2** [comment]
> @Lotfy2 can you provide me your contact please?

Sure 
Telegram : @MostafaMohamedGamal

**Comment by thompsona88** [comment]
Can I make a translation in Chinese? I have had experience translating Whitepaper, ANN, Bounty, Web .... This is my previous job: https://docs.google.com/spreadsheets/d/1noNeg6__CF_UdinBosyiZuS5JIgd9jLi3B9Um78hffk/edit#gid=0
Telegram: @Thompsonal
Gmail: smithanddy0@gmail.com
**PM me if accepted**

**Comment by vaultman542** [comment]
So, what about russian translation?

**Comment by serejandmyself** [comment]
@vaultman542 It is reserved already

@thompsona88 i did, no answer

**Comment by takisn19** [comment]
Dear manager, I would like to be dedicated to the Portuguese translation, please send me a message, if accepted. Telegram username: @Takisn This is my previous job 
Portfolio link: https://docs.google.com/spreadsheets/d/1gegVNewxc9W7dJxj8ZlM4VoazmgBqzCdHSpjvqdXLi4/edit?usp=sharing

**Comment by Amaralyjapan** [comment]
Dear Sir. I am ready for Japanese translation 
Bct name: Amaraly

**Comment by serejandmyself** [comment]
> Dear Sir. I am ready for Japanese translation
> Bct name: Amaraly

@Amaralyjapan Awesome! You may start IF you agree with the translation guidelines. I have sent you a PM on BTT and published them on the BTT thread

**Comment by anobtc90** [comment]
Hello. I'm ready and replied to your pm on Bitcointalk. My bitcointalk username is: anobtc, My Telegram id: @cajmartin
Thanks!

**Comment by serejandmyself** [comment]
Excellent! I replied to you

**Comment by serejandmyself** [comment]
Hey @Lotfy2 are you still working on the translation?

**Comment by serejandmyself** [comment]
@Lotfy2 Please note, that I took you off the reserve for this bounty

**Comment by Mildredin** [comment]
hello do you need turkish translation i can join translation

**Comment by kberey** [comment]
@serejandmyself I can't click the #filipino.

**Comment by taykeshi** [comment]
I can do Finnish! I'm a native Finn and study English at uni.

**Comment by serejandmyself** [comment]
> @serejandmyself I can't click the #filipino.

Already reserved it (Ken in brackets). The V is after its done =)

**Comment by serejandmyself** [comment]
> I can do Finnish! I'm a native Finn and study English at uni.

Interesting. Any translations you've done before?

**Comment by Medialisa** [comment]
hello i want to join italian translation if you need to contact me on telegram  https://t.me/Medialisa

**Comment by serejandmyself** [comment]
> hello i want to join italian translation if you need to contact me on telegram https://t.me/Medialisa

Will contact you!

**Comment by Cherylwinz** [comment]
Hello Cyber team, I'm Cherylwinz from bitcointalks , i'm a Polish translation and community management, I have been in crypto since 2019 and have a lot of experience in community management

You can see my proposal here: 
https://docs.google.com/spreadsheets/d/1sNaYIO2AswslUa_1LKTwyHRX5mx9yI9juw__gLpMwx4/edit?usp=sharing

I will create social media channels Cyber Polish and promote on it. Moreover, I have a good relationship with major crypto communities and KOLs in Polish, which can help your project with many investors in Polish. 

My email: winsomezt@gmail.com  and telegram: https://t.me/Cherylwinz

Wait to hear from you.

**Comment by lindaAme** [comment]
hello i would like to put the Arabic translation as a link to my previous work : https://bom.to/cIncxO . Please contact telegram if you need : @abicll

**Comment by serejandmyself** [comment]
@Cherylwinz Hey! We do not hire community managers. The project lives on donations and community governance. Please see the ambassador bounty program for this: https://cybercongress.ai/post/obep/

**Comment by serejandmyself** [comment]
@lindaAme Have you done any technical translations? Cybers WP is a bit more technical then your previous work

**Comment by lindaAme** [comment]
> @lindaAme Have you done any technical translations? Cybers WP is a bit more technical then your previous work

this is my job . I used to use the m.d file for my work, I guarantee I will do a good job
https://bom.to/a2NTXm

**Comment by serejandmyself** [comment]
OBEP is irrelevant
